name: GitHub Traffic Logger
on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight
  workflow_dispatch: # Allows you to run it manually whenever you want

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Generate GG Traffic Stats
        uses: jgehrcke/github-repo-stats@v1.4.2
        with:
          repository: ThiHarper/GrappleGraph
          ghtoken: ${{ secrets.GG_METRICS_TOKEN }}
          # This saves data to a branch named 'traffic' so it doesn't clutter your main code