name: GitHub Traffic Logger
on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight
  workflow_dispatch: # Allows you to run it manually whenever you want

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: GitHub Traffic Statistics
        uses: sangonzalezplus/github-traffic-report@master # Use the master version for better stability
        with:
          TOKEN: ${{ secrets.GG_METRICS_TOKEN }}
          REPOSITORY: ThiHarper/GrappleGraph
          # This saves data to a branch named 'traffic' so it doesn't clutter your main code